"""EquipmentInstanceFactory: 887.outsideItems -> HeroEquip instance parameters.

The client's battle drop pipeline (DropProp/ADC -> TypeId -> IdentifyItem star ->
JudgeDropItem DroopLimit3 band -> FightItemBag -> 887.outsideItems) fully determines
(TypeId, Star). This factory instantiates that result; it never rerolls Star.

Official data (src/x2server/data/equipment_tables.json, generated by
tools/dev/export_equipment_tables.py):
  - main attr type / minor attr types: EquibBase[TypeId] pools + weights
  - attr values: EquibAttrib[Star, src, Type].ValueSec (3 discrete tiers)
  - affix-count tiers: derived from canonical EquibAttribBD rows (MinorAttrNum)

REVIVAL_COMPATIBILITY / USER_DECISIONs (docs/decisions/compatibility/):
  - affix-count tier for 4-6 star: base 65% / max 35% (equip_attribbd_tier_selection.md)
  - ValueSec tier roll: sequential upgrade chain (equip_valuesec_tier_roll.md)

Evidence notes:
  - Minor affix types are drawn without replacement: every official EquibAttribBD
    plate (66 rows) uses distinct minor types within one item (full-dataset evidence).
  - ChanceSec has no client consumer; the chain is a compatibility interpretation.
"""
from __future__ import annotations

import json
import random
from importlib.resources import files

BASE_TIER_CHANCE = 0.65  # USER_DECISION 2026-09-25: base/Min tier 65% / max tier 35%

MIN_STAR, MAX_STAR = 1, 6


class EquipmentValidationError(ValueError):
    """outsideItem cannot be instantiated as HeroEquip."""


def load_equipment_tables() -> dict:
    return json.loads(files("x2server").joinpath("data/equipment_tables.json").read_text(encoding="utf-8"))


def roll_value_sec(value_sec: list[int], chance_sec: list[int], rng: random.Random) -> int:
    """Sequential upgrade chain over the official 3-tier ValueSec ladder.

    REVIVAL_COMPATIBILITY (equip_valuesec_tier_roll.md): start at ValueSec[0],
    upgrade to [1] with ChanceSec[0]%, then to [2] with ChanceSec[1]%.
    [60,40] -> 40%/36%/24%; [80,20] -> 20%/64%/16%.
    """
    tier = 0
    if len(value_sec) > 1 and rng.random() * 100 < chance_sec[0]:
        tier = 1
        if len(value_sec) > 2 and rng.random() * 100 < chance_sec[1]:
            tier = 2
    return value_sec[tier]


def weighted_choice_index(types: list[int], chances: list[int], rng: random.Random) -> int:
    """Official EquibBase weighted pick (relative weights, not percentages).

    Returns the pool index so callers can draw without replacement.
    Consumes rng only when there is more than one candidate.
    """
    if len(types) == 1:
        return 0
    total = sum(chances)
    if total <= 0:
        raise EquipmentValidationError("non-positive attribute weight sum")
    pick = rng.random() * total
    upto = 0
    for index, chance in enumerate(chances):
        upto += chance
        if pick < upto:
            return index
    return len(types) - 1


class EquipmentInstanceFactory:
    """Pure factory: (TypeId, Star) -> EquipParam dict. RNG is injectable."""

    def __init__(self, data: dict | None = None, rng: random.Random | None = None):
        self.data = data or load_equipment_tables()
        self.rng = rng or random.Random()

    def is_drop_equipment(self, type_id: int) -> bool:
        """Part-level equib only; the 1245|SS|S display family has no EquibBase row."""
        return str(type_id) in self.data["equib_base"]

    def validate(self, type_id: int, star: int, quantity: int) -> None:
        if not isinstance(type_id, int) or not isinstance(star, int) or not isinstance(quantity, int):
            raise EquipmentValidationError("type_id/star/quantity must be int")
        if str(type_id) not in self.data["equib_base"]:
            raise EquipmentValidationError(
                f"TypeId {type_id} is not a part-level equib (EquibBase row missing)")
        if not MIN_STAR <= star <= MAX_STAR:
            raise EquipmentValidationError(f"Star {star} outside legal range")
        if not 0 < quantity <= 99:
            raise EquipmentValidationError(f"quantity {quantity} outside legal range")
        if str(star) not in self.data["equib_attrib"] or str(star) not in self.data["equib_stage"]:
            raise EquipmentValidationError(f"no EquibAttrib/EquibStage data for star {star}")

    def minor_count(self, star: int) -> int:
        """Initial affix count: the MinorAttrNum of the selected count-tier row.

        1-3 star have a single tier (base == max). For 4-6 star the tier choice is
        REVIVAL_COMPATIBILITY: base 65% / max 35% (equip_attribbd_tier_selection.md).
        """
        tiers = self.data["minor_count_tiers"][str(star)]
        if tiers["base"] == tiers["max"]:
            return tiers["base"]
        return tiers["base"] if self.rng.random() < BASE_TIER_CHANCE else tiers["max"]

    def _attr_ladder(self, star: int, src: str, attr_type: int) -> tuple[list[int], list[int]]:
        entry = self.data["equib_attrib"][str(star)][src].get(str(attr_type))
        if entry is None:
            raise EquipmentValidationError(f"no EquibAttrib ladder star={star} src={src} type={attr_type}")
        return entry["value_sec"], entry["chance_sec"]

    def roll_param(self, type_id: int, star: int) -> dict:
        """Roll one EquipParam. Draw order (deterministic for seeded tests):
        count tier -> main value chain -> per minor slot: type, then value chain."""
        base = self.data["equib_base"][str(type_id)]
        param: dict[str, int] = {}
        for slot in range(1, 7):
            param[f"at{slot}"] = 0
            param[f"av{slot}"] = 0
            param[f"lock{slot}"] = 0

        count = self.minor_count(star)  # first draw: count tier (base 65% / max 35%)

        main_type = base["main_attr_type"][weighted_choice_index(
            base["main_attr_type"], base["main_attr_chance"], self.rng)]
        value_sec, chance_sec = self._attr_ladder(star, "0", main_type)
        param["at1"], param["av1"] = main_type, roll_value_sec(value_sec, chance_sec, self.rng)

        pool = list(base["minor_attr_type"])
        chances = list(base["minor_attr_chance"])
        if len(pool) < count:
            raise EquipmentValidationError(f"TypeId {type_id}: minor pool smaller than affix count")
        for slot in range(2, 2 + count):
            index = weighted_choice_index(pool, chances, self.rng)
            attr_type = pool[index]
            del pool[index]
            del chances[index]
            value_sec, chance_sec = self._attr_ladder(star, "2", attr_type)
            param[f"at{slot}"] = attr_type
            param[f"av{slot}"] = roll_value_sec(value_sec, chance_sec, self.rng)
        return param


def ensure_equipment_instances(db):
    """Create or patch the 兽主 instance ledger: one canonical DDL for every creator.

    Two callers build this table - ``EquipmentService.__init__`` and this module's drop
    materializer - so a column one of them forgot would break wherever the table
    happened to be created first. ``locked`` is the 兽主 lock state behind
    C2L_LockEquip (883/884); the ``ALTER`` patches an older save whose table predates it.
    """
    db.execute("""CREATE TABLE IF NOT EXISTS equipment_instances (
        id INTEGER PRIMARY KEY AUTOINCREMENT, player_id INTEGER NOT NULL,
        type_id INTEGER NOT NULL, level INTEGER NOT NULL DEFAULT 0,
        exp INTEGER NOT NULL DEFAULT 0, star INTEGER NOT NULL,
        param TEXT NOT NULL, marker TEXT NOT NULL,
        locked INTEGER NOT NULL DEFAULT 0,
        UNIQUE(player_id,type_id,marker))""")
    columns = {row[1] for row in db.execute("PRAGMA table_info(equipment_instances)")}
    if "locked" not in columns:
        db.execute("ALTER TABLE equipment_instances ADD COLUMN locked INTEGER NOT NULL DEFAULT 0")


def materialize_instances(db, player_id: int, type_id: int, star: int, quantity: int,
                          run_uuid: str, factory: EquipmentInstanceFactory,
                          first_ordinal: int) -> list[dict]:
    """Persist `quantity` independent HeroEquip rows and return wire-ready dicts.

    Idempotent at instance level: marker = drop:{run_uuid}:{ordinal} is deterministic
    per checkout; an existing row is reused as-is (no reroll, no new id). Callers run
    inside the checkout transaction so instances and the receipt commit atomically.
    """
    factory.validate(type_id, star, quantity)
    # Same DDL as EquipmentService.__init__ so EconomyService-only callers
    # (e.g. tests, standalone settle) share one canonical ledger.
    ensure_equipment_instances(db)
    instances = []
    ordinal = first_ordinal
    for _ in range(quantity):
        marker = f"drop:{run_uuid}:{ordinal}"
        ordinal += 1
        row = db.execute(
            "SELECT id, star, param, locked FROM equipment_instances WHERE player_id=? AND type_id=? AND marker=?",
            (player_id, type_id, marker)).fetchone()
        if row is None:
            param = factory.roll_param(type_id, star)
            cursor = db.execute(
                "INSERT INTO equipment_instances (player_id, type_id, level, exp, star, param, marker) "
                "VALUES (?, ?, 0, 0, ?, ?, ?)",
                (player_id, type_id, star, json.dumps(param, sort_keys=True), marker))
            instance_id, locked = cursor.lastrowid, 0
        else:
            instance_id, star, param, locked = row[0], row[1], json.loads(row[2]), row[3]
        instances.append({"id": instance_id, "typeId": type_id, "level": 0, "exp": 0,
                          "star": star, "status": 0, "param": param, "marker": marker,
                          "lockState": locked, "timeSec": 0, "seasonId": 0})
    return instances
